sudo: required

language: node_js

cache: yarn

services:
  - docker

before_install:
  - docker pull trufflesuite/ganache-cli:latest
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest
  - docker ps -a

script:
  - yarn run lint
  - yarn run test
