version: '3'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    networks:
      - ganache
    command: ganache-cli -h 0.0.0.0 -p 8545 -i 777

  truffle:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.truffle
    networks:
      - ganache

networks:
  ganache:
